# Generated by helper script

subclone_dirichlet_gibbs_cpp <- function(mutCount, WTCount, totalCopyNumber, normalCopyNumber, copyNumberAdjustment, C, cellularity, iter, conc_param, cluster_conc) {
    .Call("_DPClust_subclone_dirichlet_gibbs_cpp", PACKAGE = "DPClust", mutCount, WTCount, totalCopyNumber, normalCopyNumber, copyNumberAdjustment, C, cellularity, iter, conc_param, cluster_conc)
}

assign_mutations_1d_cpp <- function(S_i, pi_h, boundary, sampledIters) {
    .Call("_DPClust_assign_mutations_1d_cpp", PACKAGE = "DPClust", S_i, pi_h, boundary, sampledIters)
}

assign_mutations_nd_cpp <- function(S_i, pi_h_flat, pi_h_dims, boundary, plane_vector_flat, vector_length, vector_direction, sampledIters) {
    .Call("_DPClust_assign_mutations_nd_cpp", PACKAGE = "DPClust", S_i, pi_h_flat, pi_h_dims, boundary, plane_vector_flat, vector_length, vector_direction, sampledIters)
}

get_snv_assignment_ccfs_cpp <- function(pi_h_flat, pi_h_dims, S_i, no_iters_burn_in) {
    .Call("_DPClust_get_snv_assignment_ccfs_cpp", PACKAGE = "DPClust", pi_h_flat, pi_h_dims, S_i, no_iters_burn_in)
}
