# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subclone_dirichlet_gibbs_cpp <- function(mutCount, WTCount, totalCopyNumber, normalCopyNumber, copyNumberAdjustment, C, cellularity, iter, conc_param, cluster_conc, keep_aux_fields, num_threads, stored_iters, log_func = NULL) {
    .Call(`_DPClust_subclone_dirichlet_gibbs_cpp`, mutCount, WTCount, totalCopyNumber, normalCopyNumber, copyNumberAdjustment, C, cellularity, iter, conc_param, cluster_conc, keep_aux_fields, num_threads, stored_iters, log_func)
}

assign_mutations_1d_cpp <- function(S_i, pi_h, boundary, sampledIters_pi, sampledIters_state) {
    .Call(`_DPClust_assign_mutations_1d_cpp`, S_i, pi_h, boundary, sampledIters_pi, sampledIters_state)
}

assign_mutations_nd_cpp <- function(S_i, pi_h_flat, pi_h_dims, boundary, plane_vector_flat, vector_length, vector_direction, sampledIters_pi, sampledIters_state) {
    .Call(`_DPClust_assign_mutations_nd_cpp`, S_i, pi_h_flat, pi_h_dims, boundary, plane_vector_flat, vector_length, vector_direction, sampledIters_pi, sampledIters_state)
}

get_snv_assignment_ccfs_cpp <- function(pi_h_flat, pi_h_dims, S_i, no_iters_burn_in) {
    .Call(`_DPClust_get_snv_assignment_ccfs_cpp`, pi_h_flat, pi_h_dims, S_i, no_iters_burn_in)
}

